### ISSUE TITLE
New FFox Quantum Update 62.0 (64 bit) Wipes Tabs--only manual recovery 

### ISSUE THREAD

**Issue by scootermannn** [avbhatt/tabs#3]
I was hoping this wouldn't be an issue, not fun doing manual recovery~50xtabs!  Please fix ASAP, thanks.  Ps: I'm glad I can at least find/restore-recover, but not automatic after update.

**Comment by avbhatt** [comment]
Not certain why this happened, but this extension relies on the browsers [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). If an update or something else cleared that storage, there is not much this extension can do.
